app.env: local

spring:
  datasource:
    two:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/dataSourceTwo?autoReconnect=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123123
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-idle: 100
      max-wait: 10000
      validation-query: SELECT 1
      test-while-idle: true
      time-between-eviction-runs-millis: 27800
    one:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/dataSourceOne?autoReconnect=true&characterEncoding=UTF8&&parseTime=True
      username: root
      password: 123123
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-idle: 100
      max-wait: 10000
      validation-query: SELECT 1
      test-while-idle: true
      time-between-eviction-runs-millis: 27800
